name: OPSEC & Privacy
description: Operational security, privacy, anonymity, and encryption tools
packages:
  - tor
  - torsocks
  - torbrowser-launcher
  - proxychains-ng
  - macchanger
  - bleachbit
  - firejail
  - apparmor
  - mat2
  - onionshare
  - i2pd
  - veracrypt
  - cryptomator
  - keepassxc
  - bitwarden
  - kleopatra
  - age
  - gnupg
  - mullvad-browser-bin
  - librewolf-bin
  - proton-vpn-gtk-app
  - protonmail-bridge
  - wireguard-tools
  - openvpn
  - signal-desktop
  - session-desktop-bin
  - simplex-chat-bin
  - briar-desktop
  - tomb
  - bubblewrap
  - zulucrypt
  - paperkey
  - pass
  - gopass
  - rage
  - minisign
  - signify
  - sbctl
  - lynis
  - opensnitch
  - nftables
  - ufw
