name: OSINT & Recon
description: Open source intelligence gathering, reconnaissance, and asset discovery
packages:
  - amass
  - subfinder
  - httpx
  - naabu
  - python-shodan
  - sherlock
  - phoneinfoga
  - spiderfoot
  - sn0int
  - metagoofil
  - sublist3r
  - whatweb
  - wafw00f
  - findomain
  - nuclei
  - nuclei-templates
  - recon-ng
  - maltego
  - theharvester
  - dnsenum
  - dnsrecon
  - dmitry
  - osrframework
  - urlcrazy
  - rustscan
  - masscan
  - nmap
  - zmap
  - fierce
  - photon
  - holehe
  - socialscan
  - perl-image-exiftool
