name: Wireless & RF Attacks
description: Wireless network auditing, WiFi attacks, and RF tools
packages:
  - aircrack-ng
  - kismet
  - wifite
  - hcxdumptool
  - hcxtools
  - reaver
  - pixiewps
  - hostapd-wpe
  - freeradius
  - fluxion
  - bully
  - fern-wifi-cracker
  - cowpatty
  - mdk4
  - asleap
  - eapmd5pass
  - wifi-honey
  - gnuradio
  - gqrx
  - hackrf
  - wifiphisher
