#!/usr/bin/env python3
"""Generate every derived Null Linux artifact from the canonical manifests.

Canonical sources:
  config/roles/*.yml         role identity, menu metadata, package list
  config/desktop-entries.yml tool launchers

Nothing under iso/airootfs, src/roles or docs/roles.md may be edited by hand.
Run with --check to fail when the tree differs from what would be generated.
"""

from __future__ import annotations

import argparse
import glob
import os
import sys

import yaml

ROLES_DIR = "config/roles"
ENTRIES_FILE = "config/desktop-entries.yml"
ISO_ROLES = "iso/airootfs/usr/share/nulllinux/roles"
ISO_ENTRIES = "iso/airootfs/usr/share/nulllinux/desktop-entries"
ISO_DIRS = "iso/airootfs/usr/share/desktop-directories"
ISO_MENU = "iso/airootfs/etc/xdg/menus/applications-merged/nulllinux-security.menu"
PKG_DIR = "src/roles"
ROLE_DOC = "docs/roles.md"

BANNER = "# Generated by tools/generate.py from config/. Do not edit by hand.\n"
PKGVER = "1.0.0"
PKGREL = "3"
URL = os.environ.get("NULL_CANONICAL_REPO", "inilvinilra/NullLinux")


def load_roles() -> list[dict]:
    roles = []
    for path in sorted(glob.glob(f"{ROLES_DIR}/*.yml")):
        data = yaml.safe_load(open(path, encoding="utf-8"))
        data["_path"] = path
        roles.append(data)
    return roles


def camel(role_id: str) -> str:
    """Menu category suffix: redteam -> RedTeam, osint -> OSINT."""
    special = {
        "redteam": "RedTeam",
        "blueteam": "BlueTeam",
        "osint": "OSINT",
        "opsec": "OPSEC",
        "devtools": "DevTools",
    }
    return special.get(role_id, role_id.capitalize())


def category(role_id: str) -> str:
    return f"X-NullLinux-{camel(role_id)}"


def role_runtime(role: dict) -> str:
    """Runtime role file: line-oriented key=value so shell tools never parse YAML."""
    lines = [
        "# Generated by tools/generate.py from config/. Do not edit by hand.",
        f"id={role['id']}",
        f"name={role['name']}",
        f"description={role['description']}",
        f"menu_name={role['menu_name']}",
    ]
    lines += [f"package={p}" for p in role["packages"]]
    return "\n".join(lines) + "\n"


def pkgbuild(role: dict) -> str:
    deps = "\n".join(f"  '{p}'" for p in role["packages"])
    return f"""# Generated by tools/generate.py from config/roles/{role['id']}.yml. Do not edit by hand.
pkgname=nulllinux-{role['id']}
pkgver={PKGVER}
pkgrel={PKGREL}
pkgdesc="{role['description']}"
arch=('any')
url="https://github.com/{URL}"
license=('MIT')
depends=(
{deps}
)

# Metapackage: owns no files. Installed state is read from the package database
# so that null-toolkit and pacman can never disagree about what is installed.
"""


def directory_file(role: dict) -> str:
    return (
        "[Desktop Entry]\n"
        "Type=Directory\n"
        f"Name={role['menu_name']}\n"
        f"Comment={role['description']}\n"
        f"Icon={role['menu_icon']}\n"
    )


def desktop_entry(key: str, e: dict, roles: dict[str, dict]) -> str:
    # One registered main category keeps the entry from appearing twice in generic
    # menus; Security requires System or Settings alongside it. Null Linux grouping
    # is driven entirely by the X-NullLinux-* categories and the shipped .menu file.
    cats = ["System", "Security"] + [category(r) for r in e["roles"]]

    if e["terminal"]:
        args = f" {e['args']}" if e["args"] else ""
        # --hold keeps the window open so failures stay readable.
        exec_line = f"konsole --hold -e {e['binary']}{args}"
    else:
        args = f" {e['args']}" if e["args"] else ""
        exec_line = f"{e['binary']}{args}"

    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name={e['name']}\n"
        f"Comment={e['comment']}\n"
        f"Exec={exec_line}\n"
        f"TryExec={e['binary']}\n"
        f"Icon={e['icon']}\n"
        "Terminal=false\n"
        f"Categories={';'.join(cats)};\n"
        f"X-NullLinux-Package={e['package']}\n"
    )


def menu_file(roles: list[dict]) -> str:
    blocks = []
    for r in roles:
        cat = category(r["id"])
        blocks.append(
            f"    <Menu>\n"
            f"      <Name>{cat}</Name>\n"
            f"      <Directory>nulllinux-{r['id']}.directory</Directory>\n"
            f"      <Include><Category>{cat}</Category></Include>\n"
            f"    </Menu>\n"
        )
    return (
        '<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"\n'
        '  "http://www.freedesktop.org/standards/menu-spec/menu-1.0.dtd">\n'
        "<!-- Generated by tools/generate.py. Do not edit by hand. -->\n"
        "<Menu>\n"
        "  <Name>Applications</Name>\n\n"
        "  <Menu>\n"
        "    <Name>NullLinux-Security</Name>\n"
        "    <Directory>nulllinux-security.directory</Directory>\n\n"
        + "\n".join(blocks)
        + "  </Menu>\n</Menu>\n"
    )


def role_doc(roles: list[dict], entries: dict) -> str:
    total = sum(len(r["packages"]) for r in roles)
    uniq: dict[str, list[str]] = {}
    for r in roles:
        for p in r["packages"]:
            uniq.setdefault(p, []).append(r["id"])
    shared = {p: v for p, v in uniq.items() if len(v) > 1}

    lines = [
        "# Null Linux Role Catalog",
        "",
        "Generated by `tools/generate.py` from `config/roles/`. Do not edit by hand.",
        "",
        f"{len(roles)} roles · {total} package entries · {len(uniq)} unique packages · "
        f"{len(shared)} shared across roles · {len(entries)} tool launchers",
        "",
        "| Role | Menu | Packages | Description |",
        "| --- | --- | --- | --- |",
    ]
    for r in roles:
        lines.append(
            f"| `{r['id']}` | {r['menu_name']} | {len(r['packages'])} | {r['description']} |"
        )
    lines += [
        "",
        "## Packages shared by more than one role",
        "",
        "Removing a role must never remove these while another owning role is installed.",
        "",
    ]
    for p in sorted(shared):
        lines.append(f"- `{p}` — {', '.join(sorted(shared[p]))}")
    lines.append("")
    return "\n".join(lines)


def emit(path: str, content: str, check: bool, changed: list[str]) -> None:
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old == content:
        return
    changed.append(path)
    if not check:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if anything is out of date")
    args = ap.parse_args()

    roles = load_roles()
    by_id = {r["id"]: r for r in roles}
    entries = yaml.safe_load(open(ENTRIES_FILE, encoding="utf-8"))
    changed: list[str] = []

    known = set(by_id)
    for key, e in entries.items():
        unknown = set(e["roles"]) - known
        if unknown:
            print(f"{ENTRIES_FILE}: entry '{key}' references unknown role(s) {sorted(unknown)}")
            return 1

    for r in roles:
        emit(f"{ISO_ROLES}/{r['id']}.role", role_runtime(r), args.check, changed)
        emit(f"{PKG_DIR}/nulllinux-{r['id']}/PKGBUILD", pkgbuild(r), args.check, changed)
        emit(f"{ISO_DIRS}/nulllinux-{r['id']}.directory", directory_file(r), args.check, changed)

    for key, e in entries.items():
        emit(f"{ISO_ENTRIES}/{key}.desktop", desktop_entry(key, e, by_id), args.check, changed)

    emit(ISO_MENU, menu_file(roles), args.check, changed)
    emit(ROLE_DOC, role_doc(roles, entries), args.check, changed)

    stale = [
        p
        for p in glob.glob(f"{ISO_ROLES}/*.role")
        if os.path.basename(p)[:-5] not in by_id
    ]
    if stale:
        print("stale generated files: " + ", ".join(stale))
        return 1

    if args.check:
        if changed:
            print("out of date (run tools/generate.py):")
            for p in changed:
                print(f"  {p}")
            return 1
        print(f"generated tree is up to date ({len(roles)} roles, {len(entries)} entries)")
        return 0

    print(f"generated {len(changed)} file(s) from {len(roles)} roles, {len(entries)} entries")
    for p in changed:
        print(f"  {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
